import { 
  GraduationCap, 
  School, 
  Settings, 
  Microscope, 
  Briefcase, 
  HandHelping, 
  HeartHandshake, 
  BookOpen, 
  Users, 
  Github, 
  MapPin, 
  Sigma, 
  CarFront, 
  Eye, 
  BarChart2, 
  FileBadge, 
  Network, 
  GitBranch, 
  Box, 
  Code2, 
  Server, 
  Cpu, 
  BrainCircuit, 
  Layers, 
  Database, 
  Rocket, 
  Cloud, 
  Sparkles,
  ExternalLink,
  ChevronRight,
  Download,
  FileText,
  ArrowUpRight,
  ArrowRight,
  Award,
  Zap,
  Mail,
  Linkedin,
  Send,
  Coffee,
  LucideProps
} from "lucide-react";

export const IconMap: Record<string, React.FC<LucideProps>> = {
  "graduation-cap": GraduationCap,
  "school": School,
  "settings": Settings,
  "microscope": Microscope,
  "briefcase": Briefcase,
  "hand-helping": HandHelping,
  "heart-handshake": HeartHandshake,
  "book-open": BookOpen,
  "users": Users,
  "github": Github,
  "map-pin": MapPin,
  "sigma": Sigma,
  "car-front": CarFront,
  "eye": Eye,
  "bar-chart-2": BarChart2,
  "file-badge": FileBadge,
  "network": Network,
  "git-branch": GitBranch,
  "box": Box,
  "code-2": Code2,
  "server": Server,
  "cpu": Cpu,
  "brain-circuit": BrainCircuit,
  "layers": Layers,
  "database": Database,
  "rocket": Rocket,
  "cloud": Cloud,
  "sparkles": Sparkles,
  "external-link": ExternalLink,
  "chevron-right": ChevronRight,
  "download": Download,
  "file-text": FileText,
  "arrow-up-right": ArrowUpRight,
  "arrow-right": ArrowRight,
  "award": Award,
  "zap": Zap,
  "mail": Mail,
  "linkedin": Linkedin,
  "send": Send,
  "coffee": Coffee,
};

interface DynamicIconProps extends LucideProps {
  name: string;
}

export const DynamicIcon = ({ name, ...props }: DynamicIconProps) => {
  const Icon = IconMap[name] || Zap;
  return <Icon {...props} />;
};
